version: '3.8'

services:
  backend:
    platform: linux/amd64
    container_name: backend
    image: backend:dev
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    environment:
      - USER_MANAGED_EMULATOR_PORT=${USER_MANAGED_EMULATOR_PORT}
      - DATA_FETCH_INTERVAl=${DATA_FETCH_INTERVAl}
      - APP_BACKEND_PORT=${APP_BACKEND_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - FLOW_EMULATOR_HTTP_PORT=${FLOW_EMULATOR_HTTP_PORT}
      - FLOW_EMULATOR_RPC_PORT=${FLOW_EMULATOR_RPC_PORT}
      - FLOW_ACCOUNT_ADDRESS=${FLOW_ACCOUNT_ADDRESS}
      - FLOW_ACCOUNT_PRIVATE_KEY=${FLOW_ACCOUNT_PRIVATE_KEY}
      - FLOW_ACCOUNT_PUBLIC_KEY=${FLOW_ACCOUNT_PUBLIC_KEY}
      - FLOW_DATA_STORAGE_PORT=${FLOW_DATA_STORAGE_PORT}
    expose:
      - ${APP_BACKEND_PORT}
      - ${FLOW_EMULATOR_HTTP_PORT}
      - ${FLOW_EMULATOR_RPC_PORT}
    ports:
      - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}
      - ${FLOW_EMULATOR_HTTP_PORT}:${FLOW_EMULATOR_HTTP_PORT}
      - ${FLOW_EMULATOR_RPC_PORT}:${FLOW_EMULATOR_RPC_PORT}
    networks:
      - flowser-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    links:
      - database
    restart: unless-stopped
  frontend:
    container_name: frontend
    image: frontend:dev
    build:
      context: ./frontend
      target: development
      dockerfile: ./Dockerfile
    environment:
      - APP_FRONTEND_PORT=${APP_FRONTEND_PORT}
      - REACT_APP_FLOW_ACCESS_NODE=http://localhost:${FLOW_EMULATOR_HTTP_PORT}
      - REACT_APP_API_HOST=http://localhost:${APP_BACKEND_PORT}
    expose:
      - ${APP_FRONTEND_PORT}
    ports:
      - ${APP_FRONTEND_PORT}:${APP_FRONTEND_PORT}
    networks:
      - flowser-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
  database:
    build: ./database
    container_name: database
    volumes:
      - ./database/db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27016:27017"
    networks:
      - flowser-network
  dev-wallet:
    container_name: dev-wallet
    platform: linux/amd64
    image: ghcr.io/onflow/fcl-dev-wallet:latest
    ports:
      - "8701:8701"
    environment:
      - FLOW_ACCESS_NODE=http://host.docker.internal:${FLOW_EMULATOR_HTTP_PORT} # dev wallet is not supported for user managed emulator
      - FLOW_ACCOUNT_ADDRESS=0x${FLOW_ACCOUNT_ADDRESS}
      - FLOW_ACCOUNT_KEY_ID=0
      - FLOW_ACCOUNT_PRIVATE_KEY=${FLOW_ACCOUNT_PRIVATE_KEY}
      - FLOW_ACCOUNT_PUBLIC_KEY=${FLOW_ACCOUNT_PUBLIC_KEY}
    depends_on:
      - backend

networks:
  flowser-network:
    driver: bridge
